name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:

  spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/gem_ci.yml@main"
    secrets: "inherit"

  acceptance:
    needs: "spec"
    strategy:
      matrix:
        puppet:
          - "puppet6"
          - "puppet7"
    uses: "puppetlabs/cat-github-actions/.github/workflows/gem_acceptance.yml@main"
    secrets: "inherit"
    with:
      puppet_version: ${{ matrix.puppet }}
