name: "Snyk Scan"

on:
 workflow_dispatch:

 push:
    branches:
      - "main"
jobs:
  security:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: 2.7

      - name: "Create lock"
        run: bundle lock

      - name: "Check for vulnerabilities"
        uses: "snyk/actions/ruby@master"
        with:
          command: "monitor"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_GENERAL_KEY }}

